services:
  postgres:
    image: postgres:16-alpine
    container_name: formflow-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: formflow
      POSTGRES_PASSWORD: formflow
      POSTGRES_DB: formflow
    ports:
      - '5434:5432'
    volumes:
      - formflow_pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: formflow-redis
    restart: unless-stopped
    ports:
      - '6380:6379'
    volumes:
      - formflow_redis_data:/data

volumes:
  formflow_pg_data:
  formflow_redis_data:
